import type { Metadata } from 'next'
import { inter } from '@/lib/fonts'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import { AuthProvider } from '@/context/auth'
import { LocationProvider } from '@/context/location'
import { ReactQueryClient } from '@/components/tanstack-query'
import { ToastifyProvider } from '@/components/toastify'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClient>
          <AuthProvider>
            <LocationProvider>
              {children}

              <ToastifyProvider />
            </LocationProvider>
          </AuthProvider>
        </ReactQueryClient>
      </body>
    </html>
  )
}
