import type { Metadata } from 'next'
import { inter } from '@/lib/fonts'
import './globals.css'
import { AuthProvider } from '@/context/auth'
import { ReactQueryClient } from '@/components/tanstack-query'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClient>
          <AuthProvider>{children}</AuthProvider>
        </ReactQueryClient>
      </body>
    </html>
  )
}
